name: Cert Sites Scraper

on:
  schedule:
    # 6:00 AM IST (IST = UTC+5:30) → 00:30 UTC
    - cron: '30 0 * * *'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pytz playwright

      - name: Install Playwright browsers
        run: python -m playwright install chromium

      - name: Run cert sites scraper
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main_cert_sites.py
