name: Device Checker

on:
  schedule:
    # Runs at 8:00 PM IST (2:30 PM UTC) every day
    - cron: '30 14 * * *'
  
  # Allows manual triggering from GitHub Actions tab
  workflow_dispatch:

jobs:
  check-devices:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas pytz filelock lxml html5lib beautifulsoup4
    
    - name: Run device checker
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python main.py
    
    - name: Commit progress file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --staged --quiet || git commit -m "Update device progress - $(date)"
        git push
