name: Device Checker

on:
  schedule:
    # Runs at 5:00 PM IST (11:30 AM UTC) every day
    - cron: '30 11 * * *'
  
  # Allows manual triggering from GitHub Actions tab
  workflow_dispatch:

jobs:
  check-devices:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # This gives permission to commit back to repo
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0  # Fetch full history
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas pytz filelock lxml html5lib beautifulsoup4
    
    - name: Run device checker
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python main.py
    
    - name: Commit and push progress file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check if there are any changes
        if [ -n "$(git status --porcelain)" ]; then
          echo "Changes detected, committing..."
          git add device_progress.json
          git commit -m "Update device progress - $(date '+%Y-%m-%d %H:%M:%S')"
          git push
        else
          echo "No changes to commit"
